version: '3.1'
services:
  backend-gpt:
    restart: always
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes: 
      - mongo-data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 12345

volumes:
  mongo-data:
